apiVersion: v1
kind: ServiceAccount
metadata:
  name: volm
  namespace: volm-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: volm
  namespace: volm-test
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - persistentvolumeclaims
    verbs:
      - watch
      - get
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: volm
  namespace: volm-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: volm
subjects:
  - kind: ServiceAccount
    name: volm
    namespace: volm-test