apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volm-test-pvc-1
  namespace: volm-test
  annotations:
    test: "1234"
  labels:
    pvci.txn2.com/service: pvci
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
  storageClassName: rook-ceph-block
