apiVersion: v1
kind: Pod
metadata:
  name: pvc2-attached-pod
  namespace: volm-test
spec:
  containers:
    - name: mc
      image: minio/mc:RELEASE.2021-05-18T03-39-44Z
      command:
        - "/usr/bin/tail"
      args:
        - "-f"
        - "/dev/null"
      volumeMounts:
        - mountPath: /data/volm-test-pvc-2
          name: volm-test-pvc-2
  volumes:
    - name: volm-test-pvc-2
      persistentVolumeClaim:
        claimName: volm-test-pvc-2